"""Auth tests — pure logic only, no DB required.

SPEC §5.1 four-case access resolution + bcrypt round-trip.
"""
from __future__ import annotations

from app.models.user import User
from app.services.auth import (
    hash_password,
    resolve_accessible_property_ids,
    verify_password,
)


def _user(**kw) -> User:
    u = User()
    u.id = kw.get("id", 1)
    u.username = kw.get("username", "alice")
    u.password_hash = kw.get("password_hash", "")
    u.is_active = kw.get("is_active", True)
    u.is_staff = kw.get("is_staff", False)
    u.is_superuser = kw.get("is_superuser", False)
    return u


class TestResolveAccessibleProperties:
    """SPEC §5.1 four cases."""

    def test_anonymous_has_no_access(self):
        # Anonymous user → no properties.
        assert resolve_accessible_property_ids(
            None, all_property_ids=[1, 2, 3], grants=[]
        ) == set()

    def test_inactive_user_has_no_access(self):
        u = _user(is_active=False)
        assert resolve_accessible_property_ids(
            u, all_property_ids=[1, 2, 3], grants=[1]
        ) == set()

    def test_superuser_sees_all(self):
        # Superuser → all properties.
        u = _user(is_superuser=True)
        assert resolve_accessible_property_ids(
            u, all_property_ids=[1, 2, 3], grants=[]
        ) == {1, 2, 3}

    def test_authenticated_no_grants_has_no_access(self):
        # Non-superuser with no grants → no properties.
        u = _user()
        assert resolve_accessible_property_ids(
            u, all_property_ids=[1, 2, 3], grants=[]
        ) == set()

    def test_authenticated_with_grants_sees_only_those(self):
        # Authenticated user with grants → only those properties.
        u = _user()
        assert resolve_accessible_property_ids(
            u, all_property_ids=[1, 2, 3, 4, 5], grants=[2, 5]
        ) == {2, 5}

    def test_grants_outside_all_property_ids(self):
        # If a grant references a deleted property, the resolver still
        # returns it — the caller's downstream join will filter it out
        # naturally. Defensive but not aggressive.
        u = _user()
        assert resolve_accessible_property_ids(
            u, all_property_ids=[1, 2], grants=[2, 99]
        ) == {2, 99}


class TestPasswordHashing:
    def test_hash_and_verify_round_trip(self):
        h = hash_password("hunter2")
        assert h != "hunter2"
        assert verify_password("hunter2", h)

    def test_wrong_password_rejected(self):
        h = hash_password("hunter2")
        assert verify_password("wrong", h) is False

    def test_empty_hash_rejected(self):
        assert verify_password("anything", "") is False

    def test_garbage_hash_rejected(self):
        # Should not raise — returns False for unverifiable hashes.
        assert verify_password("anything", "not-a-bcrypt-hash") is False


class TestDjangoPbkdf2:
    """Django legacy users were migrated with `pbkdf2_sha256$...` hashes;
    `verify_password` recognises that format alongside bcrypt."""

    def test_known_django_hash_verifies(self):
        # Hash generated by Django 4.x:
        #   make_password("hunter2", "saltsalt", "pbkdf2_sha256")
        # Iteration count of 260000 matches the default for that release.
        import base64
        import hashlib

        # Build the expected hash exactly the way Django would, so the test
        # is self-contained (no Django dep needed).
        salt = "saltsalt"
        iterations = 260000
        raw = hashlib.pbkdf2_hmac(
            "sha256", b"hunter2", salt.encode(), iterations, dklen=32
        )
        django_hash = (
            f"pbkdf2_sha256${iterations}${salt}${base64.b64encode(raw).decode()}"
        )

        assert verify_password("hunter2", django_hash)
        assert verify_password("wrong", django_hash) is False

    def test_django_hash_with_different_iteration_count(self):
        """Django bumps the default iteration count over time. We parse it
        from the hash, so older + newer hashes both verify."""
        import base64
        import hashlib

        for iters in (180000, 260000, 600000, 720000):
            salt = "abcd1234"
            raw = hashlib.pbkdf2_hmac(
                "sha256", b"correct", salt.encode(), iters, dklen=32
            )
            h = f"pbkdf2_sha256${iters}${salt}${base64.b64encode(raw).decode()}"
            assert verify_password("correct", h), f"failed at {iters} iters"

    def test_malformed_pbkdf2_rejected(self):
        # Wrong number of $-separated parts
        assert verify_password("x", "pbkdf2_sha256$260000$saltonly") is False
        # Non-numeric iteration count
        assert verify_password("x", "pbkdf2_sha256$NOPE$salt$aGFzaA==") is False
        # Wrong algo prefix
        assert verify_password("x", "pbkdf2_md5$260000$salt$aGFzaA==") is False
