/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/access": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant Access */
        post: operations["grant_access_api_v1_admin_access_post"];
        /** Revoke Access */
        delete: operations["revoke_access_api_v1_admin_access_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/areas/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Area
         * @description SPEC §6.1 — live eero validation. Operator confirms the network_id
         *     + name + eero count before saving.
         */
        post: operations["preview_area_api_v1_admin_areas_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/areas/{area_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Common Area */
        put: operations["update_common_area_api_v1_admin_areas__area_id__put"];
        post?: never;
        /** Delete Common Area */
        delete: operations["delete_common_area_api_v1_admin_areas__area_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/clli/olt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Olt Cllis */
        get: operations["list_olt_cllis_api_v1_admin_clli_olt_get"];
        put?: never;
        /** Create Olt Clli */
        post: operations["create_olt_clli_api_v1_admin_clli_olt_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/clli/olt/{clli_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Olt Clli */
        delete: operations["delete_olt_clli_api_v1_admin_clli_olt__clli_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/clli/seven-fifty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Seven Fifty Cllis */
        get: operations["list_seven_fifty_cllis_api_v1_admin_clli_seven_fifty_get"];
        put?: never;
        /** Create Seven Fifty Clli */
        post: operations["create_seven_fifty_clli_api_v1_admin_clli_seven_fifty_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/clli/seven-fifty/{clli_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Seven Fifty Clli */
        delete: operations["delete_seven_fifty_clli_api_v1_admin_clli_seven_fifty__clli_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Maintenance */
        post: operations["create_maintenance_api_v1_admin_maintenance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/maintenance/{m_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Maintenance */
        put: operations["update_maintenance_api_v1_admin_maintenance__m_id__put"];
        post?: never;
        /** Delete Maintenance */
        delete: operations["delete_maintenance_api_v1_admin_maintenance__m_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Properties */
        get: operations["list_properties_api_v1_admin_properties_get"];
        put?: never;
        /** Create Property */
        post: operations["create_property_api_v1_admin_properties_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Property */
        put: operations["update_property_api_v1_admin_properties__property_id__put"];
        post?: never;
        /** Delete Property */
        delete: operations["delete_property_api_v1_admin_properties__property_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/properties/{property_id}/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Common Area */
        post: operations["create_common_area_api_v1_admin_properties__property_id__areas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/areas/{area_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Common-area detail (SPEC §5.6)
         * @description `area_id` is the network_id (e.g. `AKS-001`). Mock-mode short-circuits;
         *     real-mode enforces per-property access via the parent property.
         */
        get: operations["get_area_api_v1_areas__area_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dashboard
         * @description Per-user filtered dashboard.
         *
         *     Mock path returns the full set (dev convenience). Real path filters
         *     properties to those the caller has access to.
         */
        get: operations["get_dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Server-Sent Events stream of dashboard invalidations (SPEC §5.4)
         * @description Long-lived SSE connection. Emits:
         *
         *       • `hello`              — handshake on connect
         *       • `dashboard.invalidate` — client should re-fetch `/api/v1/dashboard`
         *       • `:heartbeat` comments  — keep-alives so proxies don't time out
         *
         *     Falls back to 30s polling on the client if the connection drops.
         */
        get: operations["get_dashboard_stream_api_v1_dashboard_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/maintenance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Active future scheduled maintenance windows + affected properties
         * @description SPEC §5.4 — feeds the dashboard's "Scheduled Maintenance" card.
         */
        get: operations["get_maintenance_api_v1_maintenance_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Property detail (drives the dashboard drawer)
         * @description Property detail.
         *
         *     Mock path uses string IDs ("aks", "prk", …) so we can't pre-validate
         *     via `require_property_access` (which expects int). The DB path enforces
         *     per-property access inline.
         */
        get: operations["get_property_api_v1_properties__property_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}/device-counts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Connected-devices time series for stacked-area chart
         * @description Critical, must-retain feature (SPEC §3 / README backend contract).
         *
         *     `ssid` omitted → totals (canonical `ssid=""` rows in `connected_device_count`).
         *     `ssid` present → filtered series. Same timestamps drive both views.
         */
        get: operations["get_device_counts_api_v1_properties__property_id__device_counts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a PDF WiFi network report for the property (SPEC §5.7)
         * @description `POST /api/v1/properties/{id}/report` `{ssids: [...]}` → streams PDF.
         *
         *     Empty `ssids` means "include all" (matches the current Django app).
         */
        post: operations["post_property_report_api_v1_properties__property_id__report_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/properties/{property_id}/ssids": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Distinct SSIDs seen for this property in the window
         * @description SPEC §7 — feeds the SSID dropdown on the Property Detail page.
         */
        get: operations["get_property_ssids_api_v1_properties__property_id__ssids_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Global search across properties, common areas, and network IDs
         * @description SPEC §5.4 / §8.3 — global search bar in the header / Cmd+K palette.
         */
        get: operations["get_search_api_v1_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AffectedPropertyOut */
        AffectedPropertyOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /** AlertItem */
        AlertItem: {
            /**
             * Acknowledged
             * @default false
             */
            acknowledged: boolean;
            /** Device */
            device?: string | null;
            /** Id */
            id: string;
            /** Message */
            message: string;
            /** Network */
            network: string;
            /** Property */
            property: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "critical" | "warning" | "info";
            /** Time */
            time: string;
        };
        /** AreaDetailResponse */
        AreaDetailResponse: {
            /** Connected Total */
            connected_total: number;
            /** Description */
            description?: string | null;
            /** Eero Units */
            eero_units: components["schemas"]["EeroUnitRow"][];
            /** Id */
            id: string;
            /** Insight Url */
            insight_url: string;
            /** Is Online */
            is_online: boolean;
            /** Last Checked */
            last_checked?: string | null;
            /** Location Name */
            location_name: string;
            /**
             * Location Type
             * @enum {string}
             */
            location_type: "indoor" | "outdoor";
            /** Network Id */
            network_id: string;
            /** Network Name */
            network_name?: string | null;
            /** Property Id */
            property_id: string;
            /** Property Name */
            property_name: string;
            /** Ssid */
            ssid?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "online" | "degraded" | "offline";
            /** Status History */
            status_history: components["schemas"]["StatusHistoryPoint"][];
            /** Wan Ip */
            wan_ip?: string | null;
        };
        /** AreaPreviewRequest */
        AreaPreviewRequest: {
            /** Api Endpoint */
            api_endpoint?: string | null;
            /** Network Id */
            network_id: string;
        };
        /**
         * AreaPreviewResponse
         * @description Returned by `POST /api/v1/admin/areas/preview`.
         *
         *     Lets the operator confirm a `network_id` actually exists and belongs to
         *     the right network before saving. The number of eero units is what they
         *     use as a sanity check.
         */
        AreaPreviewResponse: {
            /**
             * Eero Count
             * @default 0
             */
            eero_count: number;
            /** Error */
            error?: string | null;
            /**
             * Is Online
             * @default false
             */
            is_online: boolean;
            /** Network Id */
            network_id: string;
            /** Network Name */
            network_name?: string | null;
            /** Ssid */
            ssid?: string | null;
            /** Wan Ip */
            wan_ip?: string | null;
        };
        /** ClliCreate */
        ClliCreate: {
            /** Clli Code */
            clli_code: string;
            /** Description */
            description?: string | null;
        };
        /** ClliOut */
        ClliOut: {
            /** Clli Code */
            clli_code: string;
            /** Description */
            description: string | null;
            /** Id */
            id: number;
        };
        /** CommonAreaCreate */
        CommonAreaCreate: {
            /** Api Endpoint */
            api_endpoint?: string | null;
            /** Description */
            description?: string | null;
            /** Island */
            island?: ("oahu" | "maui" | "big-island" | "kauai" | "molokai" | "lanai" | "hawaii") | null;
            /** Location Name */
            location_name: string;
            /**
             * Location Type
             * @default indoor
             * @enum {string}
             */
            location_type: "indoor" | "outdoor";
            /** Network Id */
            network_id: string;
        };
        /** CommonAreaOut */
        CommonAreaOut: {
            /** Description */
            description: string | null;
            /** Id */
            id: number;
            /** Is Online */
            is_online: boolean;
            /** Island */
            island: ("oahu" | "maui" | "big-island" | "kauai" | "molokai" | "lanai" | "hawaii") | null;
            /** Last Checked */
            last_checked: string | null;
            /** Location Name */
            location_name: string;
            /**
             * Location Type
             * @enum {string}
             */
            location_type: "indoor" | "outdoor";
            /** Network Id */
            network_id: string;
            /** Network Name */
            network_name: string | null;
            /** Property Id */
            property_id: number;
            /** Ssid */
            ssid: string | null;
            /** Wan Ip */
            wan_ip: string | null;
        };
        /** CommonAreaUpdate */
        CommonAreaUpdate: {
            /** Api Endpoint */
            api_endpoint?: string | null;
            /** Description */
            description?: string | null;
            /** Island */
            island?: ("oahu" | "maui" | "big-island" | "kauai" | "molokai" | "lanai" | "hawaii") | null;
            /** Location Name */
            location_name?: string | null;
            /** Location Type */
            location_type?: ("indoor" | "outdoor") | null;
        };
        /** CurrentUserResponse */
        CurrentUserResponse: {
            /** Accessible Property Ids */
            accessible_property_ids?: number[];
            /** Email */
            email?: string | null;
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /** Is Staff */
            is_staff: boolean;
            /** Is Superuser */
            is_superuser: boolean;
            /** Username */
            username: string;
        };
        /** DashboardResponse */
        DashboardResponse: {
            /** Alerts */
            alerts: components["schemas"]["AlertItem"][];
            /** Available Ssids */
            available_ssids?: string[];
            /** Avg Latency Ms */
            avg_latency_ms: number;
            /** Degraded Count */
            degraded_count: number;
            /** Generated At */
            generated_at: string;
            /** Heatmap */
            heatmap: number[][];
            heatmap_peak: components["schemas"]["HeatCallout"];
            heatmap_quiet: components["schemas"]["HeatCallout"];
            hero_chart: components["schemas"]["DeviceCountsResponse"];
            /** Hst Now */
            hst_now: string;
            /** Islands */
            islands: components["schemas"]["IslandSummary"][];
            /** Maintenance */
            maintenance?: components["schemas"]["MaintenanceWindow"][];
            /** Online Count */
            online_count: number;
            /** Outage Count */
            outage_count: number;
            /** Properties */
            properties: components["schemas"]["PropertyPin"][];
            /** Total Devices */
            total_devices: number;
            /** Total Networks */
            total_networks: number;
            /** Total Properties */
            total_properties: number;
        };
        /** DeviceCountSeries */
        DeviceCountSeries: {
            /** Color */
            color: string;
            /** Data */
            data: number[];
            /** Network Id */
            network_id: string;
            /** Network Name */
            network_name: string;
        };
        /**
         * DeviceCountsResponse
         * @description Contract for `GET /api/v1/properties/{id}/device-counts`.
         *
         *     Same shape is embedded into the dashboard hero chart so the frontend can
         *     use a single component for both views.
         */
        DeviceCountsResponse: {
            /** Series */
            series: components["schemas"]["DeviceCountSeries"][];
            /** Ssid */
            ssid?: string | null;
            /** Timestamps */
            timestamps: string[];
        };
        /** DeviceRow */
        DeviceRow: {
            /** Firmware Version */
            firmware_version?: string | null;
            /** Location Type */
            location_type?: ("indoor" | "outdoor") | null;
            /** Mac */
            mac: string;
            /** Model */
            model: string;
            /** Name */
            name: string;
            /** Online */
            online: boolean;
            /** Rssi */
            rssi: number;
        };
        /** EeroUnitRow */
        EeroUnitRow: {
            /**
             * Connected Count
             * @default 0
             */
            connected_count: number;
            /** Firmware Version */
            firmware_version?: string | null;
            /** Is Online */
            is_online: boolean;
            /** Location */
            location?: string | null;
            /**
             * Location Type
             * @enum {string}
             */
            location_type: "indoor" | "outdoor";
            /** Model */
            model?: string | null;
            /** Serial */
            serial: string;
        };
        /** GrantOut */
        GrantOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Property Id */
            property_id: number;
            /** User Id */
            user_id: number;
        };
        /** GrantRequest */
        GrantRequest: {
            /** Property Id */
            property_id: number;
            /** User Id */
            user_id: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatCallout */
        HeatCallout: {
            /** Count */
            count: number;
            /** Day */
            day: string;
            /** Hour */
            hour: number;
        };
        /** IslandSummary */
        IslandSummary: {
            /** Devices */
            devices: number;
            /**
             * Island
             * @enum {string}
             */
            island: "oahu" | "maui" | "big-island" | "kauai" | "molokai" | "lanai";
            /** Label */
            label: string;
            /** Networks */
            networks: number;
            /** Offline */
            offline: number;
            /** Properties */
            properties: number;
            /**
             * Status
             * @enum {string}
             */
            status: "online" | "degraded" | "offline";
        };
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** MaintenanceCreate */
        MaintenanceCreate: {
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Island
             * @enum {string}
             */
            island: "all" | "oahu" | "maui" | "big-island" | "kauai" | "molokai" | "lanai" | "hawaii";
            /** Olt Clli Codes */
            olt_clli_codes?: string[];
            /**
             * Scheduled
             * Format: date-time
             */
            scheduled: string;
            /** Seven Fifty Clli Codes */
            seven_fifty_clli_codes?: string[];
        };
        /** MaintenanceOut */
        MaintenanceOut: {
            /** Affected Properties */
            affected_properties?: components["schemas"]["AffectedPropertyOut"][];
            /** Id */
            id: number;
            /** Is Active */
            is_active: boolean;
            /**
             * Island
             * @enum {string}
             */
            island: "all" | "oahu" | "maui" | "big-island" | "kauai" | "molokai" | "lanai" | "hawaii";
            /** Olt Clli Codes */
            olt_clli_codes?: string[];
            /**
             * Scheduled
             * Format: date-time
             */
            scheduled: string;
            /** Seven Fifty Clli Codes */
            seven_fifty_clli_codes?: string[];
        };
        /** MaintenanceUpdate */
        MaintenanceUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Island */
            island?: ("all" | "oahu" | "maui" | "big-island" | "kauai" | "molokai" | "lanai" | "hawaii") | null;
            /** Olt Clli Codes */
            olt_clli_codes?: string[] | null;
            /** Scheduled */
            scheduled?: string | null;
            /** Seven Fifty Clli Codes */
            seven_fifty_clli_codes?: string[] | null;
        };
        /**
         * MaintenanceWindow
         * @description Light-weight wire shape for the dashboard's "Scheduled Maintenance"
         *     card. Full admin shape lives in `schemas/maintenance.py`.
         */
        MaintenanceWindow: {
            /** Affected Property Names */
            affected_property_names?: string[];
            /** Id */
            id: number;
            /** Island */
            island: string;
            /** Olt Clli Codes */
            olt_clli_codes?: string[];
            /** Scheduled */
            scheduled: string;
            /** Seven Fifty Clli Codes */
            seven_fifty_clli_codes?: string[];
        };
        /** NetworkRow */
        NetworkRow: {
            /** Color */
            color: string;
            /** Description */
            description?: string | null;
            /** Devices */
            devices: number;
            /** Last Checked */
            last_checked?: string | null;
            /** Location Type */
            location_type?: ("indoor" | "outdoor") | null;
            /** Name */
            name: string;
            /** Network Id */
            network_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "online" | "degraded" | "offline";
        };
        /** PropertyCreate */
        PropertyCreate: {
            /** Address */
            address?: string | null;
            /** Name */
            name: string;
        };
        /** PropertyDetailResponse */
        PropertyDetailResponse: {
            /** Address */
            address?: string | null;
            /** Central Office */
            central_office: string;
            chart: components["schemas"]["DeviceCountsResponse"];
            /** Created At */
            created_at?: string | null;
            /** Devices */
            devices: components["schemas"]["DeviceRow"][];
            /** Devices Count */
            devices_count: number;
            /** Eero Models */
            eero_models?: {
                [key: string]: number;
            };
            /** Firmware Versions */
            firmware_versions?: {
                [key: string]: number;
            };
            /** Id */
            id: string;
            /**
             * Island
             * @enum {string}
             */
            island: "oahu" | "maui" | "big-island" | "kauai" | "molokai" | "lanai";
            /** Name */
            name: string;
            /** Networks */
            networks: components["schemas"]["NetworkRow"][];
            /** Networks Count */
            networks_count: number;
            /**
             * Status
             * @enum {string}
             */
            status: "online" | "degraded" | "offline";
            /** Uptime Pct */
            uptime_pct: number;
        };
        /** PropertyOut */
        PropertyOut: {
            /** Address */
            address: string | null;
            /**
             * Common Areas Count
             * @default 0
             */
            common_areas_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** PropertyPin */
        PropertyPin: {
            /** Central Office */
            central_office: string;
            /** Devices */
            devices: number;
            /** Id */
            id: string;
            /**
             * Island
             * @enum {string}
             */
            island: "oahu" | "maui" | "big-island" | "kauai" | "molokai" | "lanai";
            /**
             * Lat
             * @description 0..1 normalized for the map SVG
             */
            lat: number;
            /**
             * Lng
             * @description 0..1 normalized for the map SVG
             */
            lng: number;
            /** Name */
            name: string;
            /** Networks */
            networks: number;
            /**
             * Offline Count
             * @default 0
             */
            offline_count: number;
            /** Spark */
            spark?: number[];
            /**
             * Status
             * @enum {string}
             */
            status: "online" | "degraded" | "offline";
        };
        /** PropertyUpdate */
        PropertyUpdate: {
            /** Address */
            address?: string | null;
            /** Name */
            name?: string | null;
        };
        /**
         * ReportRequest
         * @description Body of `POST /api/v1/properties/{id}/report`.
         *
         *     Empty `ssids` means "include all" — same UX as the current Django app
         *     (zero checkboxes ⇒ all SSIDs).
         */
        ReportRequest: {
            /** Ssids */
            ssids?: string[];
        };
        /** SearchResponse */
        SearchResponse: {
            /** Query */
            query: string;
            /** Results */
            results: components["schemas"]["SearchResult"][];
        };
        /** SearchResult */
        SearchResult: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "property" | "area" | "network_id";
            /** Label */
            label: string;
            /** Network Id */
            network_id?: string | null;
            /** Property Id */
            property_id: string;
            /** Sublabel */
            sublabel?: string | null;
        };
        /** StatusHistoryPoint */
        StatusHistoryPoint: {
            /** Checked At */
            checked_at: string;
            /** Is Online */
            is_online: boolean;
            /** Response Time Ms */
            response_time_ms?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    grant_access_api_v1_admin_access_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GrantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_access_api_v1_admin_access_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GrantRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_area_api_v1_admin_areas_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AreaPreviewRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaPreviewResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_common_area_api_v1_admin_areas__area_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                area_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommonAreaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommonAreaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_common_area_api_v1_admin_areas__area_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                area_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_olt_cllis_api_v1_admin_clli_olt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClliOut"][];
                };
            };
        };
    };
    create_olt_clli_api_v1_admin_clli_olt_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClliCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClliOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_olt_clli_api_v1_admin_clli_olt__clli_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clli_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_seven_fifty_cllis_api_v1_admin_clli_seven_fifty_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClliOut"][];
                };
            };
        };
    };
    create_seven_fifty_clli_api_v1_admin_clli_seven_fifty_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClliCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClliOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_seven_fifty_clli_api_v1_admin_clli_seven_fifty__clli_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clli_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_maintenance_api_v1_admin_maintenance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_maintenance_api_v1_admin_maintenance__m_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                m_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaintenanceUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaintenanceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_maintenance_api_v1_admin_maintenance__m_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                m_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_properties_api_v1_admin_properties_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyOut"][];
                };
            };
        };
    };
    create_property_api_v1_admin_properties_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_property_api_v1_admin_properties__property_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PropertyUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_property_api_v1_admin_properties__property_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_common_area_api_v1_admin_properties__property_id__areas_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommonAreaCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommonAreaOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_area_api_v1_areas__area_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                area_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AreaDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserResponse"];
                };
            };
        };
    };
    get_dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: {
                island?: string | null;
                days?: number;
                ssid?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_stream_api_v1_dashboard_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_maintenance_api_v1_maintenance_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown[];
                };
            };
        };
    };
    get_property_api_v1_properties__property_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_device_counts_api_v1_properties__property_id__device_counts_get: {
        parameters: {
            query?: {
                days?: number;
                ssid?: string | null;
            };
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceCountsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_property_report_api_v1_properties__property_id__report_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_property_ssids_api_v1_properties__property_id__ssids_get: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                property_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_search_api_v1_search_get: {
        parameters: {
            query?: {
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
