#!/usr/bin/env bash
# Idempotent native bootstrap for the WiFi Common Area Monitor rebuild.
#
# Run as the `jahama` user (the one who owns the repo). Safe to re-run; each
# step checks current state before doing work.
#
#   ./deploy/bootstrap.sh

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BACKEND="$ROOT/backend"
FRONTEND="$ROOT/frontend"
ENVFILE="$ROOT/.env"

cd "$ROOT"
echo "▸ Bootstrap from $ROOT"

# ── Backend venv ──────────────────────────────────────────────────────────────
if [[ ! -x "$BACKEND/.venv/bin/python" ]]; then
    echo "▸ Creating Python venv at backend/.venv"
    python3 -m venv "$BACKEND/.venv"
fi
echo "▸ Installing backend deps"
"$BACKEND/.venv/bin/pip" install --upgrade pip --quiet
"$BACKEND/.venv/bin/pip" install --quiet \
    "fastapi>=0.115" "uvicorn[standard]>=0.32" "pydantic>=2.9" \
    "pydantic-settings>=2.5" "sqlalchemy>=2.0" "alembic>=1.13" \
    "asyncpg>=0.29" "psycopg2-binary>=2.9" "httpx>=0.27" \
    "structlog>=24.4" "slowapi>=0.1.9" \
    "bcrypt>=4" "apscheduler>=3.10" "python-multipart>=0.0.12" \
    "pytz>=2024.1" "itsdangerous>=2" "typer>=0.12" "pyyaml>=6" \
    "reportlab>=4.0" "matplotlib>=3.8" "prometheus_client>=0.20"
# psycopg2-binary is used only by deploy/migrate_from_legacy.py (one-shot
# legacy→new DB copier); the runtime app uses asyncpg.
echo "  backend deps OK"

# ── Frontend build (Next.js standalone) ───────────────────────────────────────
echo "▸ Frontend install + build"
cd "$FRONTEND"
if [[ ! -d node_modules ]]; then
    npm install --no-audit --no-fund
fi
npm run build

# Stage standalone bundle: copy `public` and `.next/static` into the
# standalone tree so `node server.js` can serve them.
echo "▸ Staging standalone bundle"
rm -rf .next/standalone/.next/static .next/standalone/public 2>/dev/null || true
cp -r .next/static .next/standalone/.next/static
if [[ -d public ]]; then
    cp -r public .next/standalone/public
fi
echo "  frontend build OK"

# ── .env (generate once, never overwrite) ─────────────────────────────────────
cd "$ROOT"
if [[ ! -f "$ENVFILE" ]]; then
    echo "▸ Generating .env (first run)"
    SECRET_KEY="$(openssl rand -hex 32)"
    cat > "$ENVFILE" <<EOF
# Generated by deploy/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Edit by hand from here. Don't commit secrets.

# Public origin (used for FastAPI's CORS allow-list)
DOMAIN=commonplace.kokocraterlabs.com

# Bring it up in mock mode first so you can verify the stack without
# eero credentials. Flip to false (and set EERO_API_TOKEN) for real polling.
USE_MOCK_DATA=true

# Cookie signing — keep stable across restarts to preserve sessions.
SECRET_KEY=$SECRET_KEY

# Caddy fronts us with HTTPS, so the session cookie should be Secure.
SESSION_COOKIE_SECURE=true

# Logs
LOG_FORMAT=json
LOG_LEVEL=info
METRICS_ENABLED=true

# Postgres — only consulted in real mode. Filled in by deploy/sql/init.sql.
DATABASE_URL=postgresql+asyncpg://wifimon:CHANGE_ME@127.0.0.1:5432/wifimon

# eero — leave empty in mock mode.
EERO_API_TOKEN=
EERO_API_BASE_URL=https://api-user.e2ro.com/2.2/networks/

# Pushover — leave empty for the Null notifier.
PUSHOVER_APP_TOKEN=
PUSHOVER_USER_KEY=

# Allowed origins — Caddy fronts a single origin so this is mainly for
# direct-to-loopback debugging.
ALLOWED_ORIGINS=https://commonplace.kokocraterlabs.com,http://127.0.0.1:8765,http://127.0.0.1:3030
EOF
    chmod 600 "$ENVFILE"
    echo "  wrote $ENVFILE (mode 600)"
else
    echo "▸ .env already exists; leaving it alone"
fi

echo
echo "✅ Bootstrap done."
echo
echo "Next steps (require sudo):"
echo "  sudo cp deploy/systemd/*.service /etc/systemd/system/"
echo "  sudo systemctl daemon-reload"
echo "  sudo systemctl enable --now wifimon-web wifimon-frontend"
echo "  # ALSO: append the import to /etc/caddy/Caddyfile, then:"
echo "  sudo systemctl reload caddy"
