"""initial schema

Revision ID: 40f9492a92b5
Revises: 
Create Date: 2026-04-30 20:48:31.150541

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40f9492a92b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('olt_cllis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clli_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_olt_cllis')),
    sa.UniqueConstraint('clli_code', name=op.f('uq_olt_cllis_clli_code'))
    )
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_properties')),
    sa.UniqueConstraint('name', name=op.f('uq_properties_name'))
    )
    op.create_table('scheduled_maintenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('island', sa.Enum('KAUAI', 'OAHU', 'MOLOKAI', 'LANAI', 'MAUI', 'HAWAII', 'ALL', name='maintenance_island'), nullable=False),
    sa.Column('scheduled', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_maintenances'))
    )
    op.create_table('seven_fifty_cllis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clli_code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seven_fifty_cllis')),
    sa.UniqueConstraint('clli_code', name=op.f('uq_seven_fifty_cllis_clli_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('common_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('island', sa.Enum('KAUAI', 'OAHU', 'MOLOKAI', 'LANAI', 'MAUI', 'HAWAII', name='island'), nullable=True),
    sa.Column('location_type', sa.Enum('INDOOR', 'OUTDOOR', name='location_type'), server_default='indoor', nullable=False),
    sa.Column('location_name', sa.String(length=120), nullable=False),
    sa.Column('network_id', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('api_endpoint', sa.String(length=255), nullable=True),
    sa.Column('network_name', sa.String(length=255), nullable=True),
    sa.Column('ssid', sa.String(length=120), nullable=True),
    sa.Column('wan_ip', sa.String(length=45), nullable=True),
    sa.Column('is_online', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_chronic', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_common_areas_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_common_areas')),
    sa.UniqueConstraint('property_id', 'location_name', name='uq_common_areas_property_location')
    )
    op.create_index(op.f('ix_common_areas_network_id'), 'common_areas', ['network_id'], unique=True)
    op.create_index(op.f('ix_common_areas_property_id'), 'common_areas', ['property_id'], unique=False)
    op.create_table('maintenance_olt_clli',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('olt_clli_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['scheduled_maintenances.id'], name=op.f('fk_maintenance_olt_clli_maintenance_id_scheduled_maintenances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['olt_clli_id'], ['olt_cllis.id'], name=op.f('fk_maintenance_olt_clli_olt_clli_id_olt_cllis'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maintenance_id', 'olt_clli_id', name=op.f('pk_maintenance_olt_clli'))
    )
    op.create_table('maintenance_seven_fifty_clli',
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('seven_fifty_clli_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['scheduled_maintenances.id'], name=op.f('fk_maintenance_seven_fifty_clli_maintenance_id_scheduled_maintenances'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seven_fifty_clli_id'], ['seven_fifty_cllis.id'], name=op.f('fk_maintenance_seven_fifty_clli_seven_fifty_clli_id_seven_fifty_cllis'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('maintenance_id', 'seven_fifty_clli_id', name=op.f('pk_maintenance_seven_fifty_clli'))
    )
    op.create_table('property_olt_clli',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('olt_clli_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['olt_clli_id'], ['olt_cllis.id'], name=op.f('fk_property_olt_clli_olt_clli_id_olt_cllis'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_olt_clli_property_id_properties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id', 'olt_clli_id', name=op.f('pk_property_olt_clli'))
    )
    op.create_table('property_seven_fifty_clli',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('seven_fifty_clli_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_property_seven_fifty_clli_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seven_fifty_clli_id'], ['seven_fifty_cllis.id'], name=op.f('fk_property_seven_fifty_clli_seven_fifty_clli_id_seven_fifty_cllis'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id', 'seven_fifty_clli_id', name=op.f('pk_property_seven_fifty_clli'))
    )
    op.create_table('user_property_accesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_user_property_accesses_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], name=op.f('fk_user_property_accesses_property_id_properties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_property_accesses_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_property_accesses')),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_user_property_accesses_user_property')
    )
    op.create_index(op.f('ix_user_property_accesses_property_id'), 'user_property_accesses', ['property_id'], unique=False)
    op.create_index(op.f('ix_user_property_accesses_user_id'), 'user_property_accesses', ['user_id'], unique=False)
    op.create_table('connected_device_counts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('common_area_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('ssid', sa.String(length=120), server_default='', nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['common_area_id'], ['common_areas.id'], name=op.f('fk_connected_device_counts_common_area_id_common_areas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connected_device_counts'))
    )
    op.create_index('ix_connected_device_counts_common_area_timestamp', 'connected_device_counts', ['common_area_id', 'timestamp'], unique=False)
    op.create_index('ix_connected_device_counts_ssid_timestamp', 'connected_device_counts', ['ssid', 'timestamp'], unique=False)
    op.create_index('ix_connected_device_counts_timestamp_desc', 'connected_device_counts', ['timestamp'], unique=False)
    op.create_table('eero_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_area_id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('location_type', sa.Enum('INDOOR', 'OUTDOOR', name='location_type'), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('is_online', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('offline_since', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_chronic', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_notification_sent', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['common_area_id'], ['common_areas.id'], name=op.f('fk_eero_devices_common_area_id_common_areas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_eero_devices')),
    sa.UniqueConstraint('common_area_id', 'serial', name='uq_eero_devices_common_area_serial')
    )
    op.create_index(op.f('ix_eero_devices_common_area_id'), 'eero_devices', ['common_area_id'], unique=False)
    op.create_table('network_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('common_area_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), server_default='', nullable=False),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['common_area_id'], ['common_areas.id'], name=op.f('fk_network_statuses_common_area_id_common_areas'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_statuses'))
    )
    op.create_index('ix_network_statuses_checked_at_desc', 'network_statuses', ['checked_at'], unique=False)
    op.create_index('ix_network_statuses_common_area_checked_at', 'network_statuses', ['common_area_id', 'checked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_network_statuses_common_area_checked_at', table_name='network_statuses')
    op.drop_index('ix_network_statuses_checked_at_desc', table_name='network_statuses')
    op.drop_table('network_statuses')
    op.drop_index(op.f('ix_eero_devices_common_area_id'), table_name='eero_devices')
    op.drop_table('eero_devices')
    op.drop_index('ix_connected_device_counts_timestamp_desc', table_name='connected_device_counts')
    op.drop_index('ix_connected_device_counts_ssid_timestamp', table_name='connected_device_counts')
    op.drop_index('ix_connected_device_counts_common_area_timestamp', table_name='connected_device_counts')
    op.drop_table('connected_device_counts')
    op.drop_index(op.f('ix_user_property_accesses_user_id'), table_name='user_property_accesses')
    op.drop_index(op.f('ix_user_property_accesses_property_id'), table_name='user_property_accesses')
    op.drop_table('user_property_accesses')
    op.drop_table('property_seven_fifty_clli')
    op.drop_table('property_olt_clli')
    op.drop_table('maintenance_seven_fifty_clli')
    op.drop_table('maintenance_olt_clli')
    op.drop_index(op.f('ix_common_areas_property_id'), table_name='common_areas')
    op.drop_index(op.f('ix_common_areas_network_id'), table_name='common_areas')
    op.drop_table('common_areas')
    op.drop_table('users')
    op.drop_table('seven_fifty_cllis')
    op.drop_table('scheduled_maintenances')
    op.drop_table('properties')
    op.drop_table('olt_cllis')
    # ### end Alembic commands ###
